package main

// Keywords は VBA キーワードの正規ケースマップ (小文字キー → 正規表記)
var Keywords = map[string]string{
	// 制御フロー
	"if":       "If",
	"then":     "Then",
	"else":     "Else",
	"elseif":   "ElseIf",
	"end":      "End",
	"for":      "For",
	"each":     "Each",
	"to":       "To",
	"step":     "Step",
	"next":     "Next",
	"do":       "Do",
	"while":    "While",
	"loop":     "Loop",
	"until":    "Until",
	"wend":     "Wend",
	"select":   "Select",
	"case":     "Case",
	"with":     "With",
	"exit":     "Exit",
	"goto":     "GoTo",
	"gosub":    "GoSub",
	"return":   "Return",
	"stop":     "Stop",
	// 宣言
	"sub":        "Sub",
	"function":   "Function",
	"property":   "Property",
	"get":        "Get",
	"let":        "Let",
	"set":        "Set",
	"class":      "Class",
	"type":       "Type",
	"enum":       "Enum",
	"implements": "Implements",
	// 変数宣言
	"dim":     "Dim",
	"redim":   "ReDim",
	"public":  "Public",
	"private": "Private",
	"friend":  "Friend",
	"global":  "Global",
	"static":  "Static",
	"const":   "Const",
	// オプション
	"option": "Option",
	"explicit":  "Explicit",
	"base":      "Base",
	"compare":   "Compare",
	"preserve":  "Preserve",
	// データ型
	"as":       "As",
	"new":      "New",
	"boolean":  "Boolean",
	"byte":     "Byte",
	"integer":  "Integer",
	"long":     "Long",
	"single":   "Single",
	"double":   "Double",
	"currency": "Currency",
	"date":     "Date",
	"string":   "String",
	"object":    "Object",
	"variant":   "Variant",
	"nothing":   "Nothing",
	"empty":     "Empty",
	"null":      "Null",
	// 演算子・論理
	"and":  "And",
	"or":   "Or",
	"not":  "Not",
	"xor":  "Xor",
	"eqv":  "Eqv",
	"imp":  "Imp",
	"mod":  "Mod",
	"like": "Like",
	"is":   "Is",
	"in":   "In",
	// 組み込み関数 (よく使われるもの)
	"abs":       "Abs",
	"asc":       "Asc",
	"chr":       "Chr",
	"cbool":     "CBool",
	"cbyte":     "CByte",
	"ccur":      "CCur",
	"cdate":     "CDate",
	"cdbl":      "CDbl",
	"cint":      "CInt",
	"clng":      "CLng",
	"csng":      "CSng",
	"cstr":      "CStr",
	"cvar":      "CVar",
	"dateadd":    "DateAdd",
	"datediff":   "DateDiff",
	"datepart":   "DatePart",
	"dateserial": "DateSerial",
	"datevalue":  "DateValue",
	"day":        "Day",
	"hour":      "Hour",
	"instr":     "InStr",
	"instrrev":  "InStrRev",
	"int":       "Int",
	"fix":       "Fix",
	"isarray":   "IsArray",
	"isdate":    "IsDate",
	"isempty":   "IsEmpty",
	"iserror":   "IsError",
	"isnull":    "IsNull",
	"isnumeric": "IsNumeric",
	"isobject":  "IsObject",
	"join":      "Join",
	"lbound":    "LBound",
	"lcase":     "LCase",
	"left":      "Left",
	"len":       "Len",
	"ltrim":     "LTrim",
	"mid":       "Mid",
	"minute":    "Minute",
	"month":     "Month",
	"monthname": "MonthName",
	"msgbox":    "MsgBox",
	"now":       "Now",
	"replace":   "Replace",
	"right":     "Right",
	"rnd":       "Rnd",
	"rtrim":     "RTrim",
	"second":    "Second",
	"sgn":       "Sgn",
	"space":     "Space",
	"split":     "Split",
	"sqr":       "Sqr",
	"str":       "Str",
	"strcomp":   "StrComp",
	"strconv":   "StrConv",
	"time":      "Time",
	"timeserial":"TimeSerial",
	"timevalue": "TimeValue",
	"timer":     "Timer",
	"trim":      "Trim",
	"typename":  "TypeName",
	"ubound":    "UBound",
	"ucase":     "UCase",
	"val":       "Val",
	"vartype":   "VarType",
	"weekday":   "Weekday",
	"weekdayname":"WeekdayName",
	"year":      "Year",
	// その他
	"call":      "Call",
	"on":        "On",
	"error":     "Error",
	"resume":    "Resume",
	"byval":     "ByVal",
	"byref":     "ByRef",
	"optional":  "Optional",
	"paramarray":"ParamArray",
	"me":        "Me",
	"withevents":"WithEvents",
	"declare":   "Declare",
	"lib":       "Lib",
	"alias":     "Alias",
	"true":      "True",
	"false":     "False",
	"debug":     "Debug",
	"print":     "Print",
	"attribute": "Attribute",
}

// indentStarters はインデントを増加させるキーワードパターン
// (行頭のトークンを小文字にして比較)
var indentStarters = []string{
	"if",
	"for",
	"do",
	"while",
	"select",
	"with",
	"function",
	"sub",
	"property",
	"class",
	"type",
	"enum",
}

// indentEnders はインデントを減少させるキーワードパターン
var indentEnders = []string{
	"end",
	"else",
	"elseif",
	"loop",
	"next",
	"wend",
	"case",
}

// headerPassthrough は常にカラム0で出力する行の先頭トークン (小文字)
var headerPassthrough = []string{
	"attribute",
	"begin",
	"end",  // class module の END ブロック (depth > 0 のときのみ特別扱いは不要、End系は通常処理)
	"version",
}
